Acard\FrontendBundle\Entity\City:
    type: entity
    table: cities
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        label: { type: string(255), nullable: false }
        name: { type: string(255), nullable: false }
        lat: { type: float, nullable: false }
        lng: { type: float, nullable: false }

    manyToOne:
        province:
            targetEntity: Acard\FrontendBundle\Entity\Province
            reversedBy: events
    
    oneToMany:
        surgeries:
            targetEntity: Surgeries
            mappedBy: cities
