<?php

namespace Acard\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompetitionFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionFormRepository extends EntityRepository
{
}
