<?php

namespace Acard\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryNewsRepository extends EntityRepository {
    
}
