<?php

namespace Acard\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository {

    public function findAll() {
        $query = $this->createQueryBuilder('n')
                ->getQuery();
        return $query;
    }

    public function findAllVisible() {
        $query = $this->createQueryBuilder('n')
                ->where('n.hidden = 0')
                ->orderBy('n.dateFrom', 'DESC')
                ->getQuery();
        return $query;
    }

    public function findAllVisibleForPagging($currentPage = 1, $limit = 4) {
        $query = $this->createQueryBuilder('n')
                ->where('n.hidden = 0')
                ->orderBy('n.dateFrom', 'DESC')
                ->getQuery();

        $paginator = new Paginator($query);
        $paginator->getQuery()
                ->setFirstResult($limit * ($currentPage - 1)) // Offset
                ->setMaxResults($limit); // Limit
        return $paginator;
    }

}
