<?php

namespace Acard\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurgeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurgeriesRepository extends EntityRepository {

    public function findCities(){
        return $this->getEntityManager()->createQuery('SELECT c.id, c.name FROM AcardFrontendBundle:Surgeries s JOIN s.city c GROUP BY c.name ORDER BY c.name ASC')->getResult();
    }
    
    public function findByCity($cityId){
        return $this->getEntityManager()
                ->createQuery('SELECT s FROM AcardFrontendBundle:Surgeries s JOIN s.city c WHERE c.id = :city_id ORDER BY s.name ASC')
                ->setParameter('city_id', $cityId)
                ->getResult();
    }
}
